// Generated by CoffeeScript 1.6.2
(function() {
  var BaseFnDecorator;

  BaseFnDecorator = (function() {
    /*
    */
    function BaseFnDecorator(options) {
      this.options = options;
    }

    /*
    */


    BaseFnDecorator.prototype.run = function(data, next) {};

    /*
     creates the decorator
    */


    BaseFnDecorator.create = function(options) {};

    /*
    */


    BaseFnDecorator.test = function(value) {};

    return BaseFnDecorator;

  })();

}).call(this);
