// Generated by CoffeeScript 1.6.2
(function() {
  var FnDecor, type;

  type = require("type-component");

  FnDecor = (function() {
    function FnDecor() {}

    /*
    */


    FnDecor.prototype.test = function(fn) {
      return type(fn) === "function";
    };

    FnDecor.prototype.create = function(fn) {
      return fn;
    };

    return FnDecor;

  })();

  module.exports = function() {
    return new FnDecor();
  };

}).call(this);
