// Generated by CoffeeScript 1.6.2
(function() {
  var Stepper, step, type;

  type = require("type-component");

  step = require("../utils/step");

  Stepper = (function() {
    /*
    */
    function Stepper(_funwrap) {
      this._funwrap = _funwrap;
    }

    /*
    */


    Stepper.prototype.test = function(steps) {
      return type(steps) === "array";
    };

    /*
    */


    Stepper.prototype.create = function(steps) {
      var _this = this;

      steps = steps.map(function(step) {
        return _this._funwrap.decorate(step);
      });
      return function() {
        return step(Array.prototype.slice.call(arguments, 0), steps);
      };
    };

    return Stepper;

  })();

  module.exports = function(funwrap) {
    return new Stepper(funwrap);
  };

}).call(this);
