// Generated by CoffeeScript 1.6.2
(function() {
  var Funwrap, decor, factories;

  decor = require("./decor");

  factories = require("factories");

  Funwrap = (function() {
    /*
    */
    function Funwrap() {
      this._decorators = factories.any([]);
      this.use(this.mediator = decor.mediator(this));
      this.use(decor.fn());
      this.use(decor.stepper(this));
    }

    /*
    */


    Funwrap.prototype.decorate = function() {
      var steps;

      steps = Array.prototype.slice.call(arguments, 0);
      if (steps.length === 1) {
        steps = steps[0];
      }
      return this._decorators.create(steps);
    };

    /*
    */


    Funwrap.prototype.use = function() {
      var _ref;

      return (_ref = this._decorators.factories).push.apply(_ref, arguments);
    };

    return Funwrap;

  })();

  module.exports = function() {
    return new Funwrap();
  };

}).call(this);
